WITH_EXTRA_MODULES = 1

## lfs
CFLAGS_EXTRA += -I../../modules/luafilesystem/src
EXTRA_O += ../../modules/luafilesystem/src/lfs.o

## lrexlib-posix
CFLAGS_EXTRA += -I../../modules/lrexlib/src -DVERSION=\"2.9.2\"
EXTRA_O += ../../modules/lrexlib/src/common.o
# posix
EXTRA_O += ../../modules/lrexlib/src/posix/lposix.o

## lua-tz
CFLAGS_EXTRA += -I../../modules/luajit-tz/src
EXTRA_O += ../../modules/luajit-tz/src/tz.o
